pipeline:
    build:
        image: docker:latest
        environment:
            - DOCKER_HOST=unix:///tmp/host.sock
        volumes:
            - /var/run/docker.sock:/tmp/host.sock:rw
        privileged: true
        commands:
            - docker build -t pingu/orangeteamspeak:latest .
    

    docker:
        image: plugins/docker
        privileged: true        
        repo: pingu/orangeteamspeak
        auth: ${DOCKER_AUTH}
        tags:
            - latest

            
