pipeline:
  publish:
    image: plugins/docker
    privileged: true
    repo: pingu/ots3
    tags: 3.0.7.1
    secrets: [ docker_username, docker_password ]
    when:
      status: [ success ]
      branch: [ master ]
