pipeline:
    build:
        image: docker:latest
        environment:
            - DOCKER_HOST=unix:///tmp/host.sock
        volumes:
            - /var/run/docker.sock:/tmp/host.sock:rw
        privileged: true
        commands:
            - docker build -t pingu/orangeteamspeak:latest .
            - docker login --username ${DOCKER_LOGIN} --password ${DOCKER_PW}
            - docker push pingu/orangeteamspeak:latest
